// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Project: civicsheild-3d808
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJtVCHcmayZbYiSzijUWxp9hOoZrz7QuI',
    appId: '1:299870255203:web:8f2934ddb822ecfc922056',
    messagingSenderId: '299870255203',
    projectId: 'civicsheild-3d808',
    authDomain: 'civicsheild-3d808.firebaseapp.com',
    storageBucket: 'civicsheild-3d808.firebasestorage.app',
    measurementId: 'G-5HJNLZSPFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzOp8HFnKz5MuZVS305s0hmMIT1GwQ5lo',
    appId: '1:299870255203:android:02a083f18e7812b8922056',
    messagingSenderId: '299870255203',
    projectId: 'civicsheild-3d808',
    storageBucket: 'civicsheild-3d808.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz2LPIToRBU6br1vpg-4JVpKxCXqSqliI',
    appId: '1:299870255203:ios:ecde756fd61c64aa922056',
    messagingSenderId: '299870255203',
    projectId: 'civicsheild-3d808',
    storageBucket: 'civicsheild-3d808.firebasestorage.app',
    androidClientId: '299870255203-5al8pspk1dr68hetuc169dncmi35o77f.apps.googleusercontent.com',
    iosClientId: '299870255203-45dpe7jns81d8l249frs1bdmhahc5hqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.civicshield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz2LPIToRBU6br1vpg-4JVpKxCXqSqliI',
    appId: '1:299870255203:ios:ecde756fd61c64aa922056',
    messagingSenderId: '299870255203',
    projectId: 'civicsheild-3d808',
    storageBucket: 'civicsheild-3d808.firebasestorage.app',
    androidClientId: '299870255203-5al8pspk1dr68hetuc169dncmi35o77f.apps.googleusercontent.com',
    iosClientId: '299870255203-45dpe7jns81d8l249frs1bdmhahc5hqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.civicshield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJtVCHcmayZbYiSzijUWxp9hOoZrz7QuI',
    appId: '1:299870255203:web:7ae47065964a49a6922056',
    messagingSenderId: '299870255203',
    projectId: 'civicsheild-3d808',
    authDomain: 'civicsheild-3d808.firebaseapp.com',
    storageBucket: 'civicsheild-3d808.firebasestorage.app',
    measurementId: 'G-0S3BT48LP9',
  );

}